server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nandira_dev
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
