server:
  port: 9081
spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nandira_auth_test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
