server:
  port: 8081

spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nandira_auth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
