server:
  port: 10081

spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/nandira_auth_prod
    username: prod_user
    password: prod_pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
